tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

# Programing
brew "anyenv"
cask "github"

# Browser
cask "google-chrome"

# Image & Video
brew "ffmpeg"
brew "imagemagick"

# Git
brew "gh"
brew "diff-so-fancy"

# zsh
brew "zsh-syntax-highlighting"
brew "zsh-completions"

# IME
cask "visual-studio-code"

# Cleaner
cask "appcleaner"
