tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

# Programing
brew "anyenv"
cask "github"

# Browser
cask "google-chrome"

# Image & Video
brew "ffmpeg"
brew "imagemagick"

# IME
cask "visual-studio-code"

# Cleaner
cask "appcleaner"

# Docker
brew "docker"
brew "docker-compose"
brew "lima"
brew "qemu"
