tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"

# Programing
brew "anyenv"

# Image & Video
brew "ffmpeg"

# Git
brew "gh"
brew "diff-so-fancy"

# zsh
brew "zsh"
brew "zsh-syntax-highlighting"
brew "zsh-completions"
