#!/bin/sh

DOTPATH=~/.dotfiles
GITHUB_URL=https://github.com/kazukitash/dotfiles.git
TARBALL_URL=https://github.com/kazukitash/dotfiles/archive/master.tar.gz
RUBY_VERSION=2.3.0

get_os() {
  case "$(uname)" in
    Linux)
      echo "linux"
      ;;
    Darwin)
      echo "osx"
      ;;
    *)
      echo "unkown"
      ;;
  esac
}

has() {
  type "$1" >/dev/null 2>&1
  return $?
}

e_newline() {
  printf "\n"
}

e_header() {
  printf "\033[37;1m%s\033[m\n" "$*"
}

e_done() {
  printf "\033[37;1m%s\033[m...\033[32mOK\033[m\n" "✔ $*"
}

e_error() {
  printf "\033[31m%s\033[m\n" "✖ $*" 1>&2
}

dotfiles_download() {
  e_newline && e_header "Downloading dotfiles..."
  if has "git"; then
    git clone --recursive "$GITHUB_URL" "$DOTPATH"
  elif has "curl" || has "wget"; then
    if has "curl"; then
      curl -L "$TARBALL_URL"
    elif has "wget"; then
      wget -O - "$TARBALL_URL"
    fi | tar xvz
    if [ ! -d dotfiles-master ]; then
      e_error "dotfiles-master: not found"
      exit 1
    fi
    mv -f dotfiles-master "$DOTPATH"
  else
    e_error "curl or wget required"
    exit 1
  fi
  e_done "Download"
}

dotfiles_deploy() {
  e_newline && e_header "Deploying dotfiles..."
  cd "$DOTPATH"
  make deploy
  e_done "Deploy"
}

dotfiles_init() {
  e_newline && e_header "Initializing dotfiles..."
  cd "$DOTPATH"
  make init
  e_done "Initialize"
}

dotfiles_logo='
      _       _    __ _ _
     | |     | |  / _(_) |
   __| | ___ | |_| |_ _| | ___  ___
  / _` |/ _ \| __|  _| | |/ _ \/ __|
  | (_| | (_) | |_| | | | |  __/\__ \
  \__,_|\___/ \__|_| |_|_|\___||___/
'

# [優れた dotfiles を設計する | TELLME.TOKYO](http://tellme.tokyo/post/2015/07/16/dotfiles/)
# 対話的には実行しない
if ! echo "$-" | grep -q "i"; then
  if [ "$0" = "${BASH_SOURCE:-}" ]; then
    # -> bash a.sh
    exit 1
  else
    # -> cat a.sh | bash
    # -> bash -c "$(cat a.sh)"
    if [ -n "${BASH_EXECUTION_STRING:-}" ] || [ -p /dev/stdin ]; then
      echo "$dotfiles_logo"
      dotfiles_download
      dotfiles_deploy
      dotfiles_init
      e_newline && e_header "Now continue with rebooting your shell"
    fi
  fi
fi
